package com.amazonaws.lambda.demo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Todos")
public class Todo {

	private String todoId;

	private String todoValue;

	private String todoEmail;

	private String todoStatus;

	@DynamoDBHashKey(attributeName = "todoId")
	@DynamoDBAutoGeneratedKey
	public String getTodoId() {
		return todoId;
	}

	public void setTodoId(String todoId) {
		this.todoId = todoId;
	}

	@DynamoDBAttribute
	public String getTodoValue() {
		return todoValue;
	}

	public void setTodoValue(String todoValue) {
		this.todoValue = todoValue;
	}

	@DynamoDBAttribute
	public String getTodoEmail() {
		return todoEmail;
	}

	public void setTodoEmail(String todoEmail) {
		this.todoEmail = todoEmail;
	}

	@DynamoDBAttribute
	public String getTodoStatus() {
		return todoStatus;
	}

	public void setTodoStatus(String todoStatus) {
		this.todoStatus = todoStatus;
	}

}
